### ISSUE TITLE
[bug] All wallets tab is empty

### ISSUE THREAD

**Issue by vanyasav** [reown-com/appkit#3128]
### Link to minimal reproducible example

https://github.com/vanyasav/angular-reown-wagmi/tree/all_wallets

### Summary

Having setup config this way:

```
    this.modal = createAppKit({
      allWallets: 'SHOW',
      adapters: [wagmiAdapter],
      networks: [immutableZkEvmTestnet],
      metadata,
      projectId: PROJECT_ID,
      includeWalletIds: [
        'c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96',
      ],
    });
```

To fix this one must add a field `featuredWalletIds` with the same array as in `includeWalletIds`

![image](https://github.com/user-attachments/assets/3a99d114-b5e7-4f5b-9581-92df6428a029)

### List of related npm package versions

```
    "@reown/appkit": "^1.1.6",
    "@reown/appkit-adapter-wagmi": "^1.1.6",
```

**Comment by dvlss** [comment]
I have the same problem

**Comment by zk118** [comment]
same here

**Comment by YadongChen** [comment]
A tip, it may be related to the following issue：

https://github.com/reown-com/appkit/pull/2961 （The number of wallets returned varies significantly across chains (e.g., 380+ for Ethereum mainnet, 60 for Base, 3 for Base Sepolia)）

It seems that when the react/web SDK performs an all-wallets query, if a chain is specified, it may not be able to query all the wallets that are "theoretically" supported.

For less popular chains, you can only manually specify: featuredWalletIds to avoid all-wallet queries being empty

------------------------

一个提示，可能与如下issue有关：

https://github.com/reown-com/appkit/pull/2961 （The number of wallets returned varies significantly across chains (e.g., 380+ for Ethereum mainnet, 60 for Base, 3 for Base Sepolia)）

似乎react / web端的SDK，进行all-wallets查询时，如果指定了一个chain，则不一定能将“理论上”支持的钱包都查询出来。

对于比较“冷门”的chain，只能手动指定：featuredWalletIds来避免all-wallet查询是空

**Comment by dvdbrv** [comment]
so the issue is still there, I'm experiencing this right now. The web3modal.org domain has expired and the api response is just Forbidden

**Comment by dvdbrv** [comment]
hopefully gets fixed soon, cause this is crippling everything

**Comment by vanyasav** [comment]
@rtomas still an issue in 1.3.2

**Comment by arein** [comment]
@vanyasav @dvdbrv @YadongChen @zk118 @dvlss apologies all - this sucks - we've fixed this a while back - can you all pls upgrade to 1.6.0 ?

Also what are y'all building? Have links to your apps? Excited to see!

**Comment by dvdbrv** [comment]
Hey @arein, ty for fixing this. When this bug happened I switched everything to Ethers so it's all okay.

I'm building Auri, a SocialFi token trading app. https://auri.one

**Comment by Morgosh** [comment]
@arein This still doesn't work, I litteraly have only 10 options to pick from, even if I dont add any limits, but might switch because of that to another wallet provider...

https://www.zkmarkets.com/

**Comment by arein** [comment]
@Morgosh mind creating a new ticket based on the latest version with repro steps and an example? We're keen to get this sorted for you but we currently don't have repro steps.

**Comment by Morgosh** [comment]
@arein the issue can also be found within your nextjs wagmi guide. Initially it showed 400+ wallets, but without changing anything switches to 50+ wallets minutes later. I am not able to figure out why and can assume only its some issue within reown api.

**Comment by arein** [comment]
@Morgosh may I still bother you to create a new issue with your exact app configuration etc? You can reference this one there.

**Comment by enesozturk** [comment]
Confirming that this issue has been resolved, please upgrade to latest version and let us know if you still encounter any issues.

https://github.com/user-attachments/assets/f3c13b1a-9d80-4e81-b490-47b4e5245594
