### ISSUE TITLE
[bug] PhantomWalletAdapter is not assignable to type BaseWalletAdapter

### ISSUE THREAD

**Issue by schellenbergk** [reown-com/appkit#3147]
### Link to minimal reproducible example

https://github.com/schellenbergk/appkit-example

### Summary

```
// App.tsx
import {createAppKit} from '@reown/appkit/react';
import {SolanaAdapter} from '@reown/appkit-adapter-solana/react';
import {solana, solanaTestnet, solanaDevnet} from '@reown/appkit/networks';
import {
  PhantomWalletAdapter,
} from '@solana/wallet-adapter-wallets';

// 0. Set up Solana Adapter
const solanaWeb3JsAdapter = new SolanaAdapter({wallets:[
    new PhantomWalletAdapter(), // Type 'PhantomWalletAdapter' is not assignable to type 'BaseWalletAdapter<string>'.
]});
```

### List of related npm package versions

```
node: v20.17.0
"@reown/appkit": "^1.1.7",
"@reown/appkit-adapter-solana": "^1.1.7",
"@solana/wallet-adapter-wallets": "^0.19.32",
```

**Comment by arein** [comment]
@schellenbergk apologies for the radio silence - this has been fixed - mind trying 1.6.0?

what are you building btw?

**Comment by brokenfiles** [comment]
> @schellenbergk apologies for the radio silence - this has been fixed - mind trying 1.6.0?
> 
> what are you building btw?

Hey, I still have the issue in the latest version (1.6.1)

```
"@reown/appkit": "^1.6.1",
```

![Screenshot](https://github.com/user-attachments/assets/40e01651-dc24-4e86-90ab-ca13ab172e73)

**Comment by tomiiide** [comment]
@brokenfiles In case you still have this problem, I fixed it by installing `@solana/web3.js` as a direct dependency of the project.

`pnpm add @solana/web3.js` or `npm install @solana/web3.js`

**Comment by ri-dev-git** [comment]
I am still facing this issue.
package.json version:
```
  "@reown/appkit": "^1.7.3",
    "@reown/appkit-adapter-solana": "^1.7.3",
    "@solana/wallet-adapter-wallets": "^0.19.36",
```

**Comment by rtomas** [comment]
sorry .. we have an issue in our docs ... 

please try 

```
// Set up Solana Adapter
export const solanaWeb3JsAdapter = new SolanaAdapter()
```
