### ISSUE TITLE
[bug] If we create an appkit for solana and evm at the same time, one of them will not load the wallets

### ISSUE THREAD

**Issue by 0xBeycan** [reown-com/appkit#3215]
### Link to minimal reproducible example

https://stackblitz.com/edit/vitejs-vite-1dpisk?file=src%2Fmain.ts

### Summary

I know about multichain but is there no way to create separate solana and evm appkit? If the user selects Solana as a network, I want to open the Solana appkit. If the user selects an EVM network, I want to open the EVM appkit, so the first option should not be entirely the appkit and the network should not be selected when clicking on the wallet, the network should be selected first and then the corresponding appkit should be created.

Or can you add a feature to completely reset the appkit? For example, while the process is running, I will reset the entire appkit process and then recreate it according to the selected network so that there is no conflict.

EVM:
<img width="770" alt="Screenshot 2024-11-07 at 21 11 46" src="https://github.com/user-attachments/assets/e02cb52e-9426-4c5e-8f2f-3c22d0e99775">

Solana:
<img width="671" alt="Screenshot 2024-11-07 at 21 11 18" src="https://github.com/user-attachments/assets/c6864872-dd5b-49c8-800c-6938b9ff9280">

If, I disable Solana side EVM is working.

I tested the following repository in two ways, directly with the structure I built and in plain form. But I can't create a separate appkit for solana and evm at the same time, they always get mixed up. I think it would be better if each appkit works independently of each other with different options.

https://github.com/BeycanDeveloper/appkit-test

### List of related npm package versions

All is latest version. I just updated today from web3modal

ethers
@reown/appkit 
@reown/appkit-adapter-ethers
@reown/appkit-adapter-solana

**Comment by BeycanDeveloper** [comment]
I solved the partial corruption with lazy load, at least whichever one opens first opens properly. However, for example, if a user wants to make consecutive transactions in ethereum and solana without refreshing the page, they will be able to connect to ethereum at first, but then they will not be able to create an appkit for solana. It also doesn't give a warning for solana but I get the following output for evm.

<img width="1800" alt="Screenshot 2024-11-07 at 22 14 50" src="https://github.com/user-attachments/assets/9fd0b1f5-25c7-45e5-89fc-9760744ec001">


Also there is don't have any way to disable event console logs

**Comment by BeycanDeveloper** [comment]
However, strangely, in the appkit-test repository I sent you, the modals open even if they are mixed together, but in my build, one modal opens and the other does not. Why could this happen?

**Comment by arein** [comment]
@0xBeycan apologies - we fixed this in 1.6.0 which was released today - what app are you building?

**Comment by 0xBeycan** [comment]
I will check it.

**Comment by 0xBeycan** [comment]
@arein Yes, the problem seems to be partially solved, but it shows directly as multichain. It would be better if it worked completely separately. Still, you are doing a good job. Thanks for your work.

**Comment by 0xBeycan** [comment]
I'm not sure, but I think there is a problem with WalletConnect showing up.

https://github.com/user-attachments/assets/0b61551b-2c4e-4577-8ac8-7c55cf7d822f

**Comment by arein** [comment]
![IMAGE 2025-01-01 13:42:55](https://github.com/user-attachments/assets/13494834-5b5f-483e-9c8b-661604a657f7)

gmgm @0xBeycan - looks like you were almost able to achieve what you want to achieve

Can you confirm that this is what you want (see screenshot and your video) - one button "Connect with EVM Wallet" and another one "Connect with Solana Wallet"?

If so then we can add this to our multichain examples as well to make sure it's covered first-class

FYI this has been requested by others as well

**Comment by 0xBeycan** [comment]
Yes, correct. I want to completely separate. Also, I think not just me. Because generally have to choose a network first. If we use blockchains exist in appkit. Your logic is okay, if is not. Mixing everything.
