### ISSUE TITLE
[bug] <appkit-button> does not reconnect on reload

### ISSUE THREAD

**Issue by webel** [reown-com/appkit#3223]
### Link to minimal reproducible example

https://github.com/webel/appkit-pure-html-example

### Summary

This is the basic vanilla js example with wagmi as seen on https://docs.reown.com/appkit/javascript/core/installation. 

Run MRE:
```
pnpm install
pnpm run dev 
// or simply: vite
```

Steps to reproduce:
1. Connect wallet
2. Reload page
3. Observe that wallet is no longer connected

https://codesandbox.io/p/github/webel/appkit-pure-html-example

Tested with wallets: metamask, phantom and brave wallet.

### List of related npm package versions

```
"@reown/appkit": "^1.3.1",
"@reown/appkit-adapter-wagmi": "^1.3.1",
"viem": "^2.21.44",
"wagmi": "^2.12.29"
```

**Comment by webel** [comment]
Looking at e.g. the next implementation, a storage and initialState is loaded and passed on to the provider. 

So, I guess, there should be an extra step to get the current state. 

```
const updateConnectionState = async () => {
	// check if key exists in local storage @appkit/connected_connector
	// if it does, try wagmi reconnect
	const connectedConnector = localStorage.getItem('@appkit/connected_connector');

	if (connectedConnector) {
		loading.set(true);
		await reconnect(wagmiAdapter.wagmiConfig);
		loading.set(false);
	}
};
```
And then I use the loading state to switch between `appkit-connect-button` and `appkit-account-button`.

**Comment by ArmmGh** [comment]
I have the same issue after upgrading "@reown/appkit-siwe" and "@reown/appkit" from v1.3 to v1.4.
I use next.js and I've thought the problem only there but it seems no. Each time I refresh the page SIWE asks to sign in.

**Comment by rtomas** [comment]
can you please confirm that this problem persist or not in latest ?
v1.5.3

**Comment by webel** [comment]
🎉 1.5.3 seems to have fixed it on initial look! Although, I find that the
connectors aren't fully re-initialised after reload.
The current connector, after reload, is a simple object of four keys rather
than a full connector with all the necessary functions.

**Comment by ArmmGh** [comment]
It is fixed on v1.5.3 but there is another issue with next.js build

**Comment by shot-codes** [comment]
I experience this issue on 1.5.3 with wagmi.

**Comment by arein** [comment]
Reload issue was fixed in 1.6.0 @webel @ArmmGh @shot-codes 

What apps are y'all building? have links?

Closing this now as fixed

**Comment by shot-codes** [comment]
@arein awesome, thanks. Building https://boost.art

**Comment by webel** [comment]
@arein hey, didn't see a 1.5.4 or update? I'm still having issues with the connector not being initialised.

I'm building peer-to-peer betting on simple games with the same seed (like, wordle or tetris). It'll be on zinged.xyz soonish, but not yet :)

**Comment by arein** [comment]
@webel coop idea ! v1.6.0 was released in npm
