### ISSUE TITLE
[bug] Cannot read properties of undefined (reading 'current') at getAccount

### ISSUE THREAD

**Issue by YVeselovskyi** [reown-com/appkit#3243]
### Link to minimal reproducible example

https://codesandbox.io/p/devbox/4hxlgt

### Summary

I am getting runtime error Cannot read properties of undefined (reading 'current') when trying to getAccount from wagmi.

### List of related npm package versions

```
"@reown/appkit": "^1.3.2",
"@reown/appkit-adapter-wagmi": "^1.3.2",
"@wagmi/core": "^2.14.6",
"viem": "^2.21.45",
"wagmi": "^2.12.32"
```

**Comment by rtomas** [comment]
can you confirm that the problem persist in latest ?

**Comment by YVeselovskyi** [comment]
@rtomas yes, it's still there

**Comment by YVeselovskyi** [comment]
```
"@reown/appkit": "^1.5.3",
"@reown/appkit-adapter-wagmi": "^1.5.3",
"@wagmi/core": "^2.15.2",
"viem": "^2.21.54",
"wagmi": "^2.13.5"
```

with the latest versions as well

**Comment by arein** [comment]
We fixed this in v1.6.0 which was released today - closing - sorry about this and feel free to get in touch

Also curious - what app are you building?

**Comment by YVeselovskyi** [comment]
@arein I am building a web-app with hybrid auth, like web3 and web2 :) 

https://4hxlgt-5173.csb.app/ - actually I still see this issue

**Comment by YVeselovskyi** [comment]
@arein even an example from here - https://github.com/reown-com/appkit/tree/main/examples/html-wagmi is not working, there are errors in console and disconnect is not working.
