### ISSUE TITLE
[bug] Network Switch & Sign Message Issues on Mobile Wallet via WalletConnect

### ISSUE THREAD

**Issue by Sidharth1013** [reown-com/appkit#3788]
### Summary

When using MetaMask Mobile to log into the AppKit Lab demo locally via WalletConnect, switching to a network that is not already added in the wallet (e.g., BSC Testnet) does not prompt the expected permission request. Instead, the app briefly displays "Approve in Wallet" for 2-3 seconds before switching the network on the app. However, the network does not get added or switched in the mobile wallet.

Additionally, when attempting to Sign Message, the network automatically switches back to Ethereum Mainnet or Sepolia Testnet instead of processing the signature request on the selected network (which was not initially available in the wallet). This behavior is inconsistent and prevents proper interaction on custom networks.

### Expected Behavior
- When switching to a network that is not added in the mobile wallet, WalletConnect should trigger a permission request for the user to Add and - Switch the Network in MetaMask Mobile.
- Once switched, the selected network should persist and not revert back when signing messages.
- For transaction-related interactions (e.g., sending tokens), the provider should correctly calculate the gas price without errors.

### Current Behavior
- No permission prompt appears when switching to an unadded network.
- The network switch does not reflect on MetaMask Mobile.
- Upon signing a message, the network automatically switches back to Ethereum Mainnet/Sepolia instead of proceeding with the signature.
- For BSC Testnet, sending tokens fails due to a provider error while trying to calculate gas price.

## Steps to Reproduce
- Log into the AppKit Lab demo locally via WalletConnect using MetaMask Mobile.
- Switch to a network not previously added in the mobile wallet.
- Observe that there is no permission request to add/switch the network in MetaMask Mobile.
- Click SIGN MESSAGE while on the unadded network.
- Notice that instead of the selected network, the network displayed on the mobile wallet is used for signing.

<img width="601" alt="Image" src="https://github.com/user-attachments/assets/0d2de3bb-2e53-4d56-92e3-d37156c9f6bc" />
<img width="889" alt="Image" src="https://github.com/user-attachments/assets/14c1c930-7609-458a-b4b8-c9bf85918624" />
<img width="601" alt="Image" src="https://github.com/user-attachments/assets/c62ee278-1522-4a7b-ae74-022360addf99" />

**On trying Sign Message with bscTestnet shown on the app, it uses the network shown in the mobile wallet instead**
![Image](https://github.com/user-attachments/assets/1ce39a05-9703-465a-9ae0-b49b631310ee)

### List of related npm package versions

Using the repo with appkit version 1.6.5

### Node.js Version

18.20.6

### Package Manager

pnpm@9.5.0

**Comment by Sam-Newman** [comment]
Thanks for raising this, we are looking into it!

**Comment by Sidharth1013** [comment]
> Thanks for raising this, we are looking into it!

Hey any updates regarding this?

**Comment by arein** [comment]
@Sidharth1013 we're pretty sure we've fixed this in v1.6.9

**Comment by Sidharth1013** [comment]
> [@Sidharth1013](https://github.com/Sidharth1013) we're pretty sure we've fixed this in v1.6.9

Hey,
I tested the new version, and the issue still persists when switching to BSC Testnet. While the latest update correctly prompts the mobile wallet to add the new network, the network briefly switches to BSC Testnet before reverting back to the previous network.

I’ve attached a screen recording demonstrating the issue. Given that this has been ongoing for over a month, I’d appreciate it if you could reopen the issue and prioritise a resolution.

https://drive.google.com/file/d/1fAGCIV74MrfLfnq0SmoldDDdw_mJsKVx/view?usp=sharing

**Comment by arein** [comment]
@Sidharth1013 ACK

**Comment by Sidharth1013** [comment]
For mobile wallets that don’t have the chain added, the Choose Network modal currently disables the network, preventing users from switching to it. It would be more user-friendly if the Add Network prompt was displayed for this case as well, allowing users to add and switch to the network.

Regarding the MetaMask issue, I noticed that when a new network is added, the chainId from the hook updates correctly. However, the defaultChainId in the WalletConnect provider state does not reflect this change. I think this could be what's causing the issue.

**Comment by arein** [comment]
> Regarding the MetaMask issue, I noticed that when a new network is added, the chainId from the hook updates correctly. However, the defaultChainId in the WalletConnect provider state does not reflect this change. I think this could be what's causing the issue.

We are expecting a major improvement of MetaMask Mobile's chain switching behavior in the next update or the one after. See https://github.com/MetaMask/metamask-mobile/pull/13515

**Comment by Sidharth1013** [comment]
@arein 
Currently, we use @web3modal/ethers, which handles this scenario without any issues. You can test it by visiting [testnet.multipli.fi](https://testnet.multipli.fi/), connecting to the dApp using MetaMask Mobile, and switching to BSC Testnet directly from the dApp without having the network added in the mobile wallet. How is it working without any issues in that case?

**Comment by arein** [comment]
> [@arein](https://github.com/arein) Currently, we use `@web3modal/ethers`, which handles this scenario without any issues. However, since `@web3modal` does not have a fallback for adding networks, we manually request `wallet_addEthereumChain `from our code if the network is not added.
> 
> You can test it by visiting [testnet.multipli.fi](https://testnet.multipli.fi/), connecting to the dApp using MetaMask Mobile, and switching to BSC Testnet directly from the dApp without having the network added in the mobile wallet. How is it working without any issues in that case?

Thanks @Sidharth1013 . We'll discuss internally tomorrow and give an update soon!

**Comment by Sidharth1013** [comment]
Hey @arein 
Any updates?
