### ISSUE TITLE
[bug] After logging in via email or social options, the signMessage operation does not work

### ISSUE THREAD

**Issue by tuzkiiiii233** [reown-com/appkit#4070]
### Link to minimal reproducible example

https://test.fusion.gallery/en

### Summary

On the first login, the signMessage modal probably persists until the user clicks ‘Sign’ to complete the signing and authentication process. And then, clicking ‘log out’ works as expected. However, when attempting to connect again, the signMessage modal briefly open and then closed without any user interaction, while the console shows error as follows:
```
{time: 1742890424103, level: 50, context: 'rw', error: Error: Request was aborted
    at AbortSignal.<anonymous> (https://test.fusion.gallery/_next/static…, msg: 'Error requesting'}
{time: 1742890424565, level: 50, context: 'rw', error: Error: Internal error: User denied account access.
    at https://test.fusion.gallery/_next/static/…, msg: 'Error connecting'}
```
Here is my code：
```
//appkit
const modal = createAppKit({
  adapters: [wagmiAdapter],
  projectId,
  networks,
  metadata: metadata,
  themeMode: 'light',
  featuredWalletIds: ['c57ca95b47569778a828d19178114f4db188b89b763c899ba0be274e97267d96'],
  features: {
    analytics: true, // Optional - defaults to your Cloud configuration
    connectMethodsOrder: ['email', 'social', 'wallet'],
  },
  defaultAccountTypes: { eip155: 'eoa' },
})

//sign
  const { isConnected} = useAccount()
  const { signMessage, data: signMsg, reset } = useSignMessage()
  useEffect(() => {
    if (isConnected && signMessage) {
        signMessage({ message: 'log in' })
    }
  }, [isConnected, signMessage])

```
Notably, this issue does not occur when logging in with a wallet. It only happens with email or social login(github/google). And it’s not always reproducible — it happens about 8 out of 10 times. I don’t know what is causing this issue. I would really appreciate any help. Thanks!

### List of related npm package versions

"wagmi": "^2.14.12",
"next": "14.2.3",
"@reown/appkit": "^1.7.0",
"@reown/appkit-adapter-wagmi": "^1.7.0",

### Node.js Version

v20.12.2

### Package Manager

yarn@1.22.22

**Comment by tuzkiiiii233** [comment]
By the way, there’s another issue. Even though I set defaultAccountTypes: { eip155: 'eoa' }, after logging in successfully, it still defaults to connecting to a smart account. This seems to be a problem.

**Comment by tuzkiiiii233** [comment]
@Sam-Newman You can get the screen recording from [here](https://github.com/tuzkiiiii233/res/blob/main/video/test.mov). Due to the unpredictability of socials and email, they have now been removed from the previously provided test URL. If any additional information is needed or if there are any updates/solutions, please contact me promptly. Thank you! 🙏

**Comment by Sam-Newman** [comment]
Hey Tuzkiii  -  That video is not playing from your link -  please can you attach it to this ticket?<br><br>I am not able to reproduce it in our environoments.<br><br>@tomas.rawski Please can you check out the config above and see if anything is incorrect?

**Comment by rtomas** [comment]
> By the way, there’s another issue. Even though I set defaultAccountTypes: { eip155: 'eoa' }, after logging in successfully, it still defaults to connecting to a smart account. This seems to be a problem.

this issue was already reported and the team is working on it ... i will bring news to this post soon

**Comment by tuzkiiiii233** [comment]
> Hey Tuzkiii - That video is not playing from your link - please can you attach it to this ticket?I am not able to reproduce it in our environoments.@tomas.rawski Please can you check out the config above and see if anything is incorrect?

The source file is too large to upload directly, so I’ve put it in the repository. The link above is the download link for my screen recording—you’ll need to click “view raw” to watch it. Or you can also try this link (https://drive.google.com/file/d/1bvGvXcUYOBlagm6EOouEJs43DIKhwry1/view?usp=drive_link).

**Comment by rtomas** [comment]
Can you replicate the signing issue in this web example?
https://appkit-web-examples-react-wagmi.reown.com/

**Comment by tuzkiiiii233** [comment]
> Can you replicate the signing issue in this web example? https://appkit-web-examples-react-wagmi.reown.com/

The issue didn’t reproduce on this website — manual signing always works fine. But in my project, the signing hook is called immediately after a successful connection.
```
  useEffect(() => {
    if (isConnected && signMessage) {
        signMessage({ message: 'I want to login on FUSION. I accept the FUSION Terms of Service.' })
    }
  }, [isConnected, signMessage])
```

I have another idea — when logging in via email, is the value of `isConnected` always consistent with the actual connection status? In my previous experience with wallet login, I noticed that as soon as the Reown modal opens, `isConnected` becomes true, even if no request has been made through any wallet yet. If I close the modal without connecting the wallet, `isConnected` remains true until the page is refreshed.
So, in the case of email login, is it possible that even though Reown shows a successful connection, Wagmi is still in the process of connecting, which causes the signMessage operation to fail? I’ll try it this way.

**Comment by rtomas** [comment]
hi @tuzkiiiii233, this issue has been fixed in 1.7.2 :)

**Comment by mbarr1111** [comment]
still see the same problem, default account is set to smart account not eoa signature

**Comment by Daargajedan** [comment]
We have the same issue... Updated to 1.7.9-f49d3d03911133c721eea4ee9afd9436e093cabe.0

Still the signature is way to long.


Correct: (Normal wallet connect)
`{"address":"0xMYADDRESS HERE","signature":"0x25c50f83e207dc6243636eeb7eb20b3ebea0c82ec2ee4b9299dd156af0a44aca571ca951911f806c1929017bd38ec5d83bff8c2a8fb529a4b8f3f55118b962461c"}`

Wrong: (Email connect)
`{"address":"0xMYADDRESS HERE","signature":"0x0000000000000000000000004e1dcf7ad4e460cfd30791ccc4f9c8a4f820ec67000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000003c000000000000000000000000000000000000000000000000000000000000003241688f0b900000000000000000000000041675c099f32341bf84bfc5382af534df5c7461a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000007a6733696a79300000000000000000000000000000000000000000000000000000000000000000000284b63e800d0000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000100000000000000000000000038869bf66a61cf6bdb996a6ae40d5853fd43b5260000000000000000000000000000000000000000000000000000000000000140000000000000000000000000a581c4a4db7175302464ff3c06380bc3270b403700000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000005354c3b6c6fd4470fd100565e521d948f2e20c6a00000000000000000000000000000000000000000000000000000000000001048d80ff0a000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000b9018ecd4ec46d4d2a6b64fe960b3d64e8b94b2234eb000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000648d0dc49f00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a581c4a4db7175302464ff3c06380bc3270b40370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000413da45273a63d0b87bda7a65d8318d8d6bcfb36b512e01ebef065ab3e9b2a73ce4c1c6941be5eb1f1921870d3447a900b9267c3986c5604f04538f92ce6fa37961f000000000000000000000000000000000000000000000000000000000000006492649264926492649264926492649264926492649264926492649264926492"}
`

**Comment by mbarr1111** [comment]
yup is because eoa by default is not working out, they said is ok but not, create an issue again because this is closed @Daargajedan  perhaps someone fix it..

**Comment by Daargajedan** [comment]
@mbarr1111 see https://github.com/reown-com/appkit/issues/4487
